'use client'

import { useState, useEffect } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { motion } from 'framer-motion'
import { ShieldCheck, ArrowRight, Loader2, KeyRound, Smartphone } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card'
import { toast } from 'sonner'

export default function OtpPage() {
  const [otp, setOtp] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const router = useRouter()
  const searchParams = useSearchParams()
  const username = searchParams.get('username')

  useEffect(() => {
    if (!username) {
      router.push('/admin/login')
    }
  }, [username, router])

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)

    try {
      const res = await fetch('/api/otp/verify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, otp })
      })

      const data = await res.json()

      if (res.ok) {
        toast.success('Verification successful!')
        router.push('/admin/dashboard')
      } else {
        toast.error(data.error || 'Invalid OTP code')
      }
    } catch (error) {
      toast.error('An error occurred during verification')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-slate-50 dark:bg-slate-950 p-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.3 }}
        className="w-full max-w-md"
      >
        <div className="flex flex-col items-center mb-8">
          <div className="w-12 h-12 bg-blue-600 rounded-2xl flex items-center justify-center mb-4 shadow-lg shadow-blue-200 dark:shadow-none">
            <ShieldCheck className="w-7 h-7 text-white" />
          </div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">SecureAuth Verification</h1>
        </div>

        <Card className="rounded-3xl border-slate-200 dark:border-slate-800 shadow-xl overflow-hidden bg-white dark:bg-slate-900">
          <CardHeader className="pt-8 px-8 pb-4 text-center">
            <div className="w-16 h-16 bg-blue-50 dark:bg-blue-900/20 rounded-full flex items-center justify-center mx-auto mb-4">
              <Smartphone className="w-8 h-8 text-blue-600" />
            </div>
            <CardTitle className="text-xl">Two-Factor Authentication</CardTitle>
            <CardDescription>
              Enter the 6-digit code sent to your device or generated by your authenticator app.
            </CardDescription>
          </CardHeader>
          <CardContent className="p-8 pt-4">
            <form onSubmit={handleVerify} className="space-y-6">
              <div className="space-y-2">
                <div className="flex justify-center gap-2">
                  <Input 
                    type="text"
                    maxLength={6}
                    placeholder="000000"
                    className="text-center text-3xl font-bold tracking-[0.5em] h-16 rounded-2xl border-slate-200 focus-visible:ring-blue-500"
                    value={otp}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) => setOtp(e.target.value.replace(/\D/g, ''))}
                    required
                    autoFocus
                  />
                </div>
              </div>
              <Button 
                type="submit" 
                className="w-full h-11 rounded-xl bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-200 dark:shadow-none font-semibold transition-all group"
                disabled={isLoading || otp.length !== 6}
              >
                {isLoading ? (
                  <Loader2 className="w-4 h-4 animate-spin mr-2" />
                ) : (
                  <>
                    Verify Code
                    <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
                  </>
                )}
              </Button>
            </form>
          </CardContent>
          <CardFooter className="bg-slate-50/50 dark:bg-slate-800/30 p-6 flex flex-col gap-3 border-t border-slate-100 dark:border-slate-800">
            <Button variant="ghost" className="text-xs text-blue-600 hover:text-blue-700 w-full rounded-xl">
              Didn't receive a code? Resend
            </Button>
            <p className="text-[10px] text-slate-400 text-center uppercase tracking-widest font-bold">
              Secure Session for {username}
            </p>
          </CardFooter>
        </Card>
      </motion.div>
    </div>
  )
}
